- name: Copy local files to local
  loop: "{{ lookup('fileglob', 'menus/local/*.ipxe', wantlist=True) }}"
  become: true
  ansible.builtin.copy:
    mode: "0644"
    owner: "{{ netboot_container_user }}"
    group: "{{ netboot_container_group }}"
    src: "{{ item }}"
    dest: "{{ netboot_base_dir }}/config/menus/local/{{ item | basename }}"

- name: Copy local files
  loop: "{{ lookup('fileglob', 'menus/local/*.ipxe', wantlist=True) }}"
  become: true
  ansible.builtin.copy:
    mode: "0644"
    owner: "{{ netboot_container_user }}"
    group: "{{ netboot_container_group }}"
    src: "{{ item }}"
    dest: "{{ netboot_base_dir }}/config/menus/{{ item | basename }}"
